# Use an official Node.js image
FROM node:18-slim

# Set work directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Expose port
EXPOSE 5173

# Command to run the application in dev mode
CMD ["npm", "run", "dev", "--", "--host"]
