from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    Table, TableStyle, Image, PageBreak, ListFlowable, ListItem
)
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch, mm
from reportlab.lib.pagesizes import A4
import os
import datetime

# ==========================
# GeM Document Constants
# ==========================
GEM_GRAY = colors.HexColor("#F2F2F2")
GEM_BLUE = colors.HexColor("#2C3E50")
BILINGUAL_FONT = "Helvetica" 

# ==========================
# Footer / Watermark
# ==========================
def add_footer(canvas, doc):
    width, height = A4
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    
    # Right: Page Numbers (Dynamic alignment)
    page_num = f"Page {doc.page}"
    canvas.drawRightString(width - 15 * mm, 12 * mm, page_num)
    
    # Left: Bid Reference
    bid_num = doc.bid_num if hasattr(doc, 'bid_num') else "DRAFT"
    canvas.drawString(15 * mm, 12 * mm, f"Bid Number: {bid_num} | Generated by ProcureSmart AI")
    
    # Bottom Center: Disclaimer
    canvas.setFont("Helvetica-Oblique", 7)
    canvas.drawCentredString(width / 2, 8 * mm, "This is an AI-drafted document intended for GeM publication. Final validation on GeM portal required.")
    canvas.restoreState()

# ==========================
# Helper: Section Title
# ==========================
def draw_section_title(elements, english_title, hindi_title, style):
    content = f"<b>{hindi_title} / {english_title}</b>"
    p = Paragraph(content, style)
    t = Table([[p]], colWidths=[7.2 * inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), GEM_GRAY),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.black),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 0.1 * inch))

# ==========================
# Main PDF Generator
# ==========================
def generate_gem_pdf(data, filename="GeM_Tender.pdf"):
    # --- STRICT VALIDATIONS & SAFE CONVERSION ---
    procurement_category = data.get("procurementCategory", "Product")
    evaluation_method = data.get("evaluationMethod", "L1")
    
    if evaluation_method not in ["L1", "QCBS", "Total Value Wise", "Total value wise evaluation"]:
        raise ValueError("Invalid Evaluation Method. Allowed: L1, QCBS, Total Value Wise.")

    if procurement_category == "Product" and not data.get("consigneeDetails"):
        raise ValueError("Consignee details mandatory for Product Tender")

    try:
        est_val = float(data.get("estimatedValue", 0) or 0)
    except (ValueError, TypeError):
        est_val = 0

    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=60
    )
    doc.bid_num = data.get("bidNumber", "DRAFT")

    elements = []
    styles = getSampleStyleSheet()
    
    # Custom Styles
    styles.add(ParagraphStyle(
        name='GemTitle', parent=styles['Title'], fontSize=16, fontName='Helvetica-Bold', alignment=1, spaceAfter=15
    ))
    styles.add(ParagraphStyle(
        name='GemSectionHeader', parent=styles['Normal'], fontSize=10, fontName='Helvetica-Bold', alignment=1,
    ))
    styles.add(ParagraphStyle(
        name='ClauseTitle', parent=styles['Normal'], fontSize=10, fontName='Helvetica-Bold', spaceBefore=10,
    ))

    # --- 1. PROFESSIONAL HEADER (Aligned Table) ---
    logo_path = "logo.png"
    if os.path.exists(logo_path):
        logo = Image(logo_path, width=1.0 * inch, height=0.6 * inch)
    else:
        logo = Paragraph("<b>GeM</b><br/><font size='7'>Government<br/>e-Marketplace</font>", styles["Normal"])
    
    header_title = Paragraph(
        "<b>Government e-Marketplace (GeM)</b><br/>"
        "<font size='8'>Effective, Efficient, and Transparent Procurement</font>", 
        styles["GemTitle"]
    )
    
    header_table = Table([[logo, header_title]], colWidths=[1.2*inch, 6*inch])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('ALIGN', (0,0), (0,0), 'LEFT'),
        ('ALIGN', (1,0), (1,0), 'CENTER'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
    ]))
    elements.append(header_table)
    elements.append(Spacer(1, 0.1 * inch))

    # Bid Meta Box
    bid_meta_text = (
        f"<b>Bid Number:</b> {doc.bid_num}<br/>"
        f"<b>Dated:</b> {datetime.datetime.now().strftime('%d-%m-%Y')}"
    )
    p_meta = Paragraph(bid_meta_text, styles["Normal"])
    meta_table = Table([[p_meta]], colWidths=[7.2*inch])
    meta_table.setStyle(TableStyle([('ALIGN', (0,0), (-1,-1), 'RIGHT')]))
    elements.append(meta_table)
    elements.append(Spacer(1, 15))

    # --- 2. BID DETAILS ---
    draw_section_title(elements, "Bid Details", "बिड विवरण", styles["GemSectionHeader"])
    
    ra_enabled = str(data.get("reverseAuction", "No")).lower() in ["enabled", "yes", "true"]
    bid_type = data.get("bidType", "Two Packet")
    if ra_enabled:
        bid_type += " with Reverse Auction"
    
    bid_rows = [
        ("Bid End Date/Time", data.get("bidEndDate")),
        ("Bid Opening Date/Time", data.get("bidOpeningDate")),
        ("Bid Offer Validity", f"{data.get('bidValidity')} Days" if data.get('bidValidity') else None),
        ("Ministry/State Name", data.get("ministry")),
        ("Department Name", data.get("department")),
        ("Organisation Name", data.get("organisation")),
        ("Item Category", data.get("category")),
        ("Total Quantity", data.get("quantity")),
        ("Bid Type", bid_type),
        ("Evaluation Method", evaluation_method),
    ]
    
    table_data = [[label, str(val)] for label, val in bid_rows if val]
    
    if "Two Packet" in bid_type:
        table_data.insert(-1, ["Technical Opening Stage", "Package 1: Technical Qualification"])
        table_data.insert(-1, ["Financial Opening Stage", "Package 2: L1 Opening for Tech-Qualified"])
    
    if ra_enabled:
         table_data.append(["RA Qualification Rule", "As per GeM RA Guidelines"])

    if table_data:
        t = Table(table_data, colWidths=[2.8 * inch, 4.2 * inch])
        t.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BACKGROUND', (0,0), (0,-1), colors.whitesmoke),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 0.2 * inch))

    # --- 3. SECURITY & FINANCE ---
    emd_required = str(data.get("emdRequired", "No")).lower() in ["yes", "true", "required"]
    epbg_required = str(data.get("epbgRequired", "No")).lower() in ["yes", "true", "required"]

    if emd_required or epbg_required:
        draw_section_title(elements, "EMD and ePBG Detail", "ईएमडी और ईपीबीजी विवरण", styles["GemSectionHeader"])
        sec_data = []
        if emd_required:
            sec_data.append(["EMD Required", "Yes"])
            sec_data.append(["EMD Amount", f"₹ {data.get('emdAmount', 0):,.2f}"])
        else:
            elements.append(Paragraph("<i>Bid Security Declaration shall be applicable in lieu of EMD.</i>", styles["Normal"]))
        
        if epbg_required:
            sec_data.append(["ePBG Required", "Yes"])
            sec_data.append(["ePBG Percentage", f"{data.get('epbgPercentage', '3')}%"])
        
        if sec_data:
            t = Table(sec_data, colWidths=[2.8 * inch, 4.2 * inch])
            t.setStyle(TableStyle([('GRID', (0, 0), (-1, -1), 0.5, colors.black), ('FONTSIZE', (0, 0), (-1, -1), 9)]))
            elements.append(t)
            elements.append(Spacer(1, 0.2 * inch))

    # --- 4. PRE-BID MEETING ---
    if str(data.get("preBidMeeting", "No")).lower() == "yes":
        draw_section_title(elements, "Pre-Bid Meeting Info", "प्री-बिड मीटिंग विवरण", styles["GemSectionHeader"])
        pb_data = [
            ["Meeting Date/Time", data.get("preBidDate", "")],
            ["Meeting Venue", data.get("preBidVenue", "Video Conferencing / Office Address")],
            ["Query Submission End", data.get("queryEndDate", "3 Days prior to meeting")]
        ]
        pb_data = [[l, str(v)] for l, v in pb_data if v]
        if pb_data:
            t = Table(pb_data, colWidths=[2.8 * inch, 4.2 * inch])
            t.setStyle(TableStyle([('GRID', (0,0), (-1,-1), 0.5, colors.black), ('FONTSIZE', (0,0), (-1,-1), 9)]))
            elements.append(t)
            elements.append(Spacer(1, 0.2 * inch))

    # --- 5. TECHNICAL / SERVICE SECTION ---
    if procurement_category == "Product":
        params = data.get("mandatoryParams", [])
        if params:
            draw_section_title(elements, "Technical Specifications & Compliance Matrix", "तकनीकी विशिष्टता और अनुपालन मैट्रिक्स", styles["GemSectionHeader"])
            elements.append(Paragraph(f"<b>Item Name:</b> {data.get('itemName', 'N/A')}", styles["Normal"]))
            
            comp_header = [["Sl", "Parameter", "Requirement", "Offered Value", "Compliance"]]
            comp_data = []
            for p in params:
                comp_data.append([p.get("slNo", ""), p.get("parameter", ""), p.get("requirement", ""), " ", " "])
            
            t = Table(comp_header + comp_data, colWidths=[0.4*inch, 1.6*inch, 2.7*inch, 1.7*inch, 0.8*inch])
            t.setStyle(TableStyle([
                ('GRID', (0, 0), (-1, -1), 0.5, colors.black), ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('BACKGROUND', (0, 0), (-1, 0), GEM_GRAY), ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ]))
            elements.append(t)
            elements.append(Spacer(1, 0.2 * inch))
    else:
        # Service section
        sla_data = [["Parameter", "Min Requirement", "Penalty Clause"]]
        if data.get('uptimePercent'): sla_data.append(["Service Uptime", f"{data.get('uptimePercent')}%", data.get("slaPenalty", "0.5% per hour")])
        if data.get('responseTime'): sla_data.append(["Response Time", data.get('responseTime'), "Liquidated Damages"])
        
        if len(sla_data) > 1:
            draw_section_title(elements, "Service Requirements & SLA", "सेवा आवश्यकताएँ और SLA", styles["GemSectionHeader"])
            t = Table(sla_data, colWidths=[2*inch, 2.5*inch, 2.5*inch])
            t.setStyle(TableStyle([('GRID', (0,0), (-1,-1), 0.5, colors.black), ('BACKGROUND', (0,0), (-1,0), GEM_GRAY)]))
            elements.append(t)
            elements.append(Spacer(1, 10))
            
            if data.get("escalationMatrix"):
                elements.append(Paragraph("<b>Escalation Matrix:</b>", styles["ClauseTitle"]))
                elements.append(Paragraph(data.get("escalationMatrix"), styles["Normal"]))
            elements.append(Spacer(1, 0.2 * inch))

    # --- 6. CONSIGNEE & DELIVERY TERMS ---
    consignees = data.get("consigneeDetails", [])
    if consignees:
        draw_section_title(elements, "Consignee Detail & Quantity", "परेषिती विवरण और मात्रा", styles["GemSectionHeader"])
        cons_header = [["S.No", "Consignee", "Address", "Quantity", "Delivery Days"]]
        cons_data = []
        for i, c in enumerate(consignees, start=1):
            cons_data.append([str(i), c.get("name", ""), c.get("address", ""), c.get("quantity", ""), data.get("deliveryPeriod", "30")])

        t = Table(cons_header + cons_data, colWidths=[0.5*inch, 1.5*inch, 3.2*inch, 0.8*inch, 1.0*inch])
        t.setStyle(TableStyle([('GRID', (0,0), (-1,-1), 0.5, colors.black), ('FONTSIZE', (0,0), (-1,-1), 8), ('BACKGROUND', (0,0), (-1,0), GEM_GRAY)]))
        elements.append(t)
        elements.append(Spacer(1, 0.2 * inch))
        
        elements.append(Paragraph("<b>Inspection & Acceptance</b>", styles["ClauseTitle"]))
        elements.append(Paragraph("Inspection shall be conducted at delivery location. Payment released after successful acceptance.", styles["Normal"]))
        elements.append(Spacer(1, 0.2 * inch))

    # --- 7. MANDATORY GeM CLAUSES (Trimmed to entered data) ---
    draw_section_title(elements, "Buyer Added Bid Specific Terms and Conditions", "विशेष नियम और शर्तें", styles["GemSectionHeader"])
    
    clauses = [("Generic", "Bidder should not be under liquidation, court receivership or bankrupt.")]
    if data.get('pastPerformance'):
        clauses.append(("Past Performance", f"Bidder/OEM should have supplied {data.get('pastPerformance')}% of bid quantity in last 3 years."))
    if data.get('miiApplicable'):
        clauses.append(("MII Preference", "Purchase preference to Make In India (MII) sellers as per Order 2017."))
    if data.get('msmePreference'):
        clauses.append(("MSE Preference", "Purchase preference to Micro and Small Enterprises as per Policy 2012."))
    
    for idx, (title, desc) in enumerate(clauses, start=1):
        elements.append(Paragraph(f"<b>{idx}. {title}</b>", styles["ClauseTitle"]))
        elements.append(Paragraph(desc, styles["Normal"]))
    
    if est_val > 10000000:
        elements.append(Paragraph(f"<b>{len(clauses)+1}. Integrity Pact Applicable</b>", styles["ClauseTitle"]))
        elements.append(Paragraph("Integrity Pact shall be signed as per CVC guidelines.", styles["Normal"]))

    elements.append(Spacer(1, 0.3 * inch))

    # --- 8. FINANCIAL BOQ ---
    boq = data.get("boqItems", [])
    if boq:
        draw_section_title(elements, "Indicative Financial Structure / BOQ", "वित्तीय संरचना", styles["GemSectionHeader"])
        boq_header = [["Sl No", "Description", "Quantity", "Unit Price", "Total Amount"]]
        boq_data = []
        for i, b in enumerate(boq):
            qty = float(b.get("quantity", 0) or 0)
            u_price = float(b.get("unitPrice", 0) or 0)
            total = qty * u_price
            boq_data.append([str(i+1), b.get("description", ""), f"{qty:,.2f}", f"₹ {u_price:,.2f}", f"₹ {total:,.2f}"])
        
        t = Table(boq_header + boq_data, colWidths=[0.5*inch, 2.5*inch, 0.8*inch, 1.0*inch, 1.0*inch])
        t.setStyle(TableStyle([('GRID', (0,0), (-1,-1), 0.5, colors.black), ('BACKGROUND', (0,0), (-1,0), GEM_GRAY), ('FONTSIZE', (0,0), (-1,-1), 9)]))
        elements.append(t)
        elements.append(Spacer(1, 0.2 * inch))

    # --- 9. FORMS & DECLARATIONS (Bidder's Undertaking) ---
    elements.append(PageBreak())
    draw_section_title(elements, "Forms and Declarations", "प्रपत्र और घोषणाएं", styles["GemSectionHeader"])
    
    undertaking_text = (
        "<b>Annexure-I: Bidder's Undertaking</b><br/><br/>"
        "To,<br/>"
        f"The Buyer, {data.get('organisation', 'Organization')}<br/><br/>"
        "I/We hereby declare that all the information and statements made in this bid are true and accept that any misinterpretation contained in it may lead to our disqualification.<br/><br/>"
        "1. We are not blacklisted by any Government organization.<br/>"
        "2. We comply with MII and MSME guidelines.<br/>"
        "3. We accept the Bid Security Declaration in lieu of EMD (if applicable).<br/><br/>"
        "<b>(Signature of Authorized Signatory with Seal)</b>"
    )
    elements.append(Paragraph(undertaking_text, styles["Normal"]))

    # --- 10. DIGITAL SIGNATURE BLOCK ---
    elements.append(Spacer(1, 0.5 * inch))
    sig_data = [
        ["<b>Digitally Signed By:</b>", ""],
        ["Name:", data.get("signatoryName", "AUTHORIZED SIGNATORY")],
        ["Designation:", data.get("signatoryDesignation", "")],
        ["Organization:", data.get("organisation", "")],
        ["Date:", datetime.datetime.now().strftime("%d-%m-%Y %H:%M:%S")],
    ]
    sig_table = Table(sig_data, colWidths=[1.5*inch, 4*inch])
    sig_table.setStyle(TableStyle([
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
    ]))
    elements.append(sig_table)

    # BUILD
    doc.build(elements, onFirstPage=add_footer, onLaterPages=add_footer)
    return filename
