import { API_BASE_URL } from "@/config";

export const draftBidDocument = async (context: string, type: string) => {
    // Mock implementation calling backend
    console.log('Drafting bid with context:', context);
    return "Draft Content Generated by AI...";
};

export const analyzeDocument = async (text: string, type: string, pages: number) => {
    console.log('Analyzing text:', text.substring(0, 50) + '...');

    // Call the backend we just created
    try {
        const response = await fetch(`${API_BASE_URL || ''}/api/tender-draft/analyze`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ query: text, source: type })
        });

        const result = await response.json();
        return { extractedData: result.extracted_data };
    } catch (error) {
        console.error("AI Analysis failed", error);
        return { extractedData: {} };
    }
};
